#!/bin/bash
# hobaectl 스크립트 파일

if [[ "$1" == "wtf" ]]; then
    echo "Do you have a lot of money? Are you not going to buy a house? Are you not going to get married?"
elif [[ "$1" == "--help" ]]; then
    echo "yes i will help you"
elif [[ "$1" == "ls" ]]; then
    # 'ls' 명령어 실행
    ls
elif [[ "$1" == "free" ]]; then
    # OS 탐지
    case "$(uname -s)" in
        Linux*)     free ;;
        Darwin*)    vm_stat ;; # macOS에서는 vm_stat을 사용할 수 있습니다.
        # 다른 OS에 대한 처리를 여기에 추가할 수 있습니다.
        *)          echo "Unsupported OS for free command" ;;
    esac
elif [[ "$1" == "info" ]]; then
    if [[ "$(uname -s)" == "Darwin" ]]; then
        system_profiler SPHardwareDataType
	echo "cpu_cores : " 
        sysctl hw.ncpu | sed 's/^/\t\t/'
	echo "ip_info_interior"
	ifconfig | grep inet -w
	echo "ip_info_external"
	ip=$(curl -s ifconfig.me)
	echo -e "\t${ip}"
    fi
elif [[ "$1" == "infra" ]]; then    #ubuntu에서 프리티어 사용시 메모리 증가를위해서 swap 설정 1GRam일경우 2G까지 swap 진행
    if [[ "$2" == "swap" ]]; then
        sudo fallocate -l 2G /swapfile
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        echo /swapfile swap swap defaults 0 0 >> /etc/fstab
        free

elif [[ "$1" == "syscheck" ]]; then
    if [[ "$(uname -s)" == "Darwin" ]]; then
        #디스크 사용량 체크
        echo "disk usage check : "  
        df -h
        #디스크 유틸리티 체크
        echo "diskutils check : "
        diskutil verifyVolume / | sed 's/^/\t\t/'  
                

        #시스템 로그 -최근 30분
        log show --predicate 'eventMessage contains "error"' --last 30m 


    fi

else
    echo "Unknown command: $1"
    echo "Use '--help' for command information."
fi

